server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/jianxincloud?useUnicode=true&characterEncoding-utr-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: fanyang123
    druid:
      validation-query: select 1
      test-while-idle: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jianxin.springcloud.entities       #所有Entity别名类所在包
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true